"use client";

import { useRef } from "react";
import type { CourseId } from "../lib/curriculum";
import { findTopic } from "../lib/curriculum";
import { getMemorizationItems } from "../lib/memorization";

type Props = {
  course: CourseId;
  topicSlug: string;
};

export default function ExportStudyGuide({ course, topicSlug }: Props) {
  const printRef = useRef<HTMLDivElement>(null);
  const topic = findTopic(course, topicSlug);
  const memorizationItems = getMemorizationItems(topicSlug);

  if (!topic) return null;

  function handlePrint() {
    if (!printRef.current) return;

    const printWindow = window.open("", "_blank");
    if (!printWindow) return;

    const content = printRef.current.innerHTML;
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>${topic.title} - Study Guide</title>
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, "SF Pro Display", sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
            h1 { font-size: 32px; margin-bottom: 8px; }
            h2 { font-size: 24px; margin-top: 32px; margin-bottom: 16px; border-bottom: 2px solid #007AFF; padding-bottom: 8px; }
            h3 { font-size: 18px; margin-top: 24px; margin-bottom: 12px; }
            .section { margin-bottom: 24px; }
            .item { margin-bottom: 12px; padding-left: 20px; }
            .memorization-table { width: 100%; border-collapse: collapse; margin-top: 16px; }
            .memorization-table th, .memorization-table td { padding: 8px 12px; text-align: left; border-bottom: 1px solid #e0e0e0; }
            .memorization-table th { background: #f5f5f7; font-weight: 600; }
            @media print { @page { margin: 1cm; } }
          </style>
        </head>
        <body>
          ${content}
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
    }, 250);
  }

  function handleExportPDF() {
    handlePrint(); // For now, use print dialog which can save as PDF
  }

  return (
    <>
      <div style={{ display: "flex", gap: 8, marginBottom: 16 }}>
        <button
          type="button"
          className="btn btnPrimary"
          onClick={handlePrint}
        >
          📄 Print Study Guide
        </button>
        <button
          type="button"
          className="btn"
          onClick={handleExportPDF}
        >
          💾 Export PDF
        </button>
      </div>

      <div ref={printRef} style={{ display: "none" }}>
        <h1>{topic.title}</h1>
        <p style={{ color: "#666", marginBottom: 32 }}>{topic.shortDesc}</p>

        <div className="section">
          <h2>Must Know</h2>
          <ul>
            {topic.mustKnow.map((item, idx) => (
              <li key={idx} className="item">{item}</li>
            ))}
          </ul>
        </div>

        <div className="section">
          <h2>Study Steps</h2>
          <ol>
            {topic.howToStudy.map((step, idx) => (
              <li key={idx} className="item">{step}</li>
            ))}
          </ol>
        </div>

        {memorizationItems.length > 0 && (
          <div className="section">
            <h2>Things to Memorize</h2>
            {memorizationItems.map((category, catIdx) => (
              <div key={catIdx} style={{ marginBottom: 24 }}>
                <h3>{category.category}</h3>
                <table className="memorization-table">
                  <thead>
                    <tr>
                      <th>Term</th>
                      <th>Value</th>
                      {category.items.some((item) => item.note) && <th>Note</th>}
                    </tr>
                  </thead>
                  <tbody>
                    {category.items.map((item, itemIdx) => (
                      <tr key={itemIdx}>
                        <td><strong>{item.term}</strong></td>
                        <td>{item.value}</td>
                        {category.items.some((i) => i.note) && <td>{item.note || ""}</td>}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            ))}
          </div>
        )}

        <div className="section">
          <h2>External Reference</h2>
          <p>
            <a href={topic.externalUrl} target="_blank" rel="noreferrer">
              {topic.externalLabel}
            </a>
          </p>
        </div>

        <div style={{ marginTop: 40, fontSize: 12, color: "#999", textAlign: "center" }}>
          Generated by OrgoPivy - Student-Centered Organic Chemistry Learning
        </div>
      </div>
    </>
  );
}
